# Generated by Django 3.2.25 on 2025-01-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('plugin', 'version', 'track')},
        ),
    ]
