# Generated by Django 3.2.25 on 2025-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_alter_release_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugindescription',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
