# Generated by Django 3.2.25 on 2025-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_plugindescription_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['version']},
        ),
        migrations.AlterField(
            model_name='plugindescription',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
